apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/alert-rules.yml
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
    scrape_configs:
      - job_name: "springboot-app"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["springboot-app:8080"]
      - job_name: "employee-app"
        metrics_path: "/v1.0.0/apis/employee/actuator/prometheus"
        static_configs:
          - targets: ["employee-app:8085"]
      - job_name: "gcp-files-app"
        metrics_path: "/actuator/prometheus"
        static_configs: 
          - targets: ["gcp-files-app:8090"]